---
- hosts: servers
  vars:
    - username: krj
    - hostname: descartes.thislanismy.lan
    - profile: home_server
    - cpu_arch: armv7
  roles:
    - alertmanager
    - common
    - descartes
    - prometheus
    - server_common
    - borg_server
