---
- hosts: servers
  vars:
    - username: krj
    - hostname: descartes.local.muumu.us
    - profile: home_server
    - cpu_arch: armv7
  roles:
    - common
    - server_common
    - descartes
    - home_network
