---
# This playbook provisions my personal laptop.

- hosts: localhost
  vars:
    - profile: home
    - borg_share: "descartes:/var/alexandria/share"
    - username: krj
    - fedora_current: 31
    - hostname: spooky.thislanismy.lan

  roles:
    - aws
    - borg_client
    - common
    - gnucash
    - graphical
    - latex
    - scheme
    - spotify
    - steam
