---
- name: Clone ~/.doom.d/
  become: yes
  become_user: "{{ username }}"
  git:
    repo: ssh://git@github.com/kylerjohnston/doom.d.git
    dest: /home/{{ username }}/.doom.d
    accept_hostkey: yes
    update: no

- name: Create ~/.local/share/applications
  file:
    path: /home/{{ username }}/.local/share/applications
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
    mode: 0700

- name: Create ~/.local/share/applications/emacsclient.desktop
  copy:
    src: emacsclient.desktop
    dest: /home/{{ username }}/.local/share/applications/emacsclient.desktop
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0664
 
- name: Create local emacs service
  copy:
    src: emacs.service
    dest: /home/{{ username }}/.config/systemd/user/emacs.service
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0664

- name: Enable emacs service
  systemd:
    name: emacs
    state: started
    enabled: yes
    scope: user
    daemon_reload: yes
  become: yes
  become_user: "{{ username }}"
