---
- name: Natural scrolling
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "true"
    state: present

- name: Super + W to close window
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/close"
    value: "['<Super>w']"
    state: present

- name: Enable night light
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
    state: present

- name: Disable night-light automatic schedule
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
    value: "false"
    state: present

- name: Set night light temperature
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
    value: "uint32 3700"
    state: present

- name: Set night light schedule from
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from"
    value: "0.0"
    state: present

- name: Set night light schedule to
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to"
    value: "0.0"
    state: present
