---
- name: Check if RPM Fusion is installed
  stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: rpmfusion

- name: Install RPM Fusion free
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
    state: present
  when: rpmfusion.stat.exists == false

- name: Check if Google Chrome repo is installed
  stat:
    path: /etc/yum.repos.d/google-chrome.repo
  register: googlechrome

- name: Install Google Chrome repo
  dnf:
    name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    state: present
  when: googlechrome.stat.exists == false

- name: Install graphical packages
  dnf:
    name:
      - '@GNOME Desktop Environment'
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - fontawesome-fonts
      - google-roboto-fonts
      - emacs
      - ffmpeg
      - firefox
      - gimp
      - google-chrome-stable
      - python3-psutil
      - tilix
    state: latest

- name: Configure emacs
  import_tasks: emacs.yml

- name: Configure GNOME
  import_tasks: gnome.yml

- name: Configure Tilix
  import_tasks: tilix.yml
