---
- name: Check if RPM Fusion is installed
  stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: rpmfusion

- name: Install RPM Fusion free
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
    state: present
  when: rpmfusion.stat.exists == false

- name: Install graphical packages
  dnf:
    name:
      - '@GNOME Desktop Environment'
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - cmake # needed for emacs vterm
      - emacs
      - fontawesome-fonts
      - ffmpeg
      - firefox
      - gimp
      - google-roboto-fonts
      - gnome-tweaks
      - libtool # also needed for emacs vterm
      - python3-psutil
      - tilix
    state: present
  become: yes

- name: Configure emacs
  import_tasks: emacs.yml

- name: Configure GNOME
  import_tasks: gnome.yml

- name: Configure Tilix
  import_tasks: tilix.yml

- name: Set default applications
  copy:
    src: mimeapps.list
    dest: /home/{{ username }}/.config/mimeapps.list
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
