---
- name: Install Blackhawk packages
  package:
    name: tortoisehg
    state: latest
  become: yes
  become_user: root

- name: See if Teams is installed
  package_facts:
    manager: auto

- name: Install Teams
  when: '"teams" not in ansible_facts.packages'
  import_tasks: install_teams.yml
