---
- name: Install required packages for home network mounts
  package:
    name:
      - fuse-afp
    state: present
  become: yes

- name: Ensure /shared
  file:
    path: /shared
    owner: root
    group: "{{ username }}"
    mode: 0775
    state: directory
  become: yes

- name: Ensure ~/home-docs
  file:
    path: /home/{{ username }}/home-docs
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0770
    state: directory

- name: Ensure /shared in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^nasty.local.muumu.us:\/media'
    line: 'nasty.local.muumu.us:/media	/shared	nfs	defaults	0 0'
  become: yes

- name: Ensure ~/home-docs in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^afpfs'
    line: 'afpfs#afp://krj:{{ afpfs_password }}@nasty.local.muumu.us/Documents	/home/krj/home-docs	fuse	user=krj,group=krj,_netdev 0 0'
  become: yes

- name: Link ~/home-docs/org to ~/org
  file:
    src: /home/{{ username }}/home-docs/org
    dest: /home/{{ username }}/org
    state: link

- name: Link ~/home-docs/Documents to ~/Documents
  file:
    src: /home/{{ username }}/home-docs/Documents
    dest: /home/{{ username }}/Documents
    state: link

- name: Link ~/shared/music to ~/Music
  file:
    src: /shared/music
    dest: /home/{{ username }}/Music
    state: link
