---
- name: Remove unused packages
  package:
    name:
      - fuse-afp
    state: absent
  become: yes

- name: Ensure /shared
  file:
    path: /shared
    owner: root
    group: "{{ username }}"
    mode: 0775
    state: directory
  become: yes

- name: Ensure ~/home-docs
  file:
    path: /home/{{ username }}/home-docs
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0770
    state: directory
  become: yes

- name: Ensure /shared in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^nasty.local.muumu.us:\/media'
    line: 'nasty.local.muumu.us:/media	/shared	nfs	defaults,_netdev	0 0'
  become: yes
  notify:
    - Daemon reload

- name: Ensure ~/home-docs in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^nasty.local.muumu.us:\/Documents'
    line: 'nasty.local.muumu.us:/Documents	/home/krj/home-docs	nfs	defaults,_netdev	0 0'
  become: yes
  notify:
    - Daemon reload

- name: Ensure afs shares removed from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^afpfs'
    state: absent
  become: yes
