---
- name: Add GPG key for rvm
  command: gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  become: yes
  become_user: root

- name: Download RVM
  get_url:
    url: https://get.rvm.io
    dest: /tmp/rvm.sh
    mode: 0755

- name: Install RVM multi-user
  command: bash /tmp/rvm.sh stable
  become: yes
  become_user: root
