---
- name: Install CUPS
  dnf:
    name: cups
    state: present
  become: yes

- name: See if Downstairs Brother is installed
  shell: lpstat -l
  register: lpstat

- name: Install Downstairs Brother printer
  shell: lpadmin -p DownstairsBrother -D "DownstairsBrother" -L "Living room" -m "foomatic:Brother-HL-2170W-ljet4d.ppd" -v http://192.168.1.3:631/ipp -E
  when: lpstat.stdout.find('DownstairsBrother') == -1
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  become_user: root
