---
- name: Install AWS CLI tools and boto3
  dnf:
    name:
      - awscli
      - python3-boto3
    state: latest

- name: Create AWS CLI config
  copy:
    src: aws_config
    dest: /home/{{ username }}/.aws/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 600
    backup: yes
