---
- name: Install AWS CLI tools and boto3
  dnf:
    name:
      - awscli
      - python3-boto3
    state: latest

- name: Create AWS CLI config
  template:
    src: aws_config.j2
    dest: /home/{{ username }}/.aws/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600
    backup: yes
    force: no
