groups:
- name: alert.rules
  rules:
  - alert: AlexandriaNotMounted
    expr: descartes_alexandria_mounted == 0
    for: 10s
    labels:
      severity: "critical"
    annotations:
      summary: "The external drive is not mounted on `descartes`."
  - alert: NoRecentBackups
    expr: last_spooky_backup > 7
    for: 1s
    labels:
      severity: "critical"
    annotations:
      summary: "No backups from spooky in the past week."
