---
- name: Install motd
  copy:
    src: motd/{{ hostname }}.motd
    dest: /etc/motd
    mode: 0644
    owner: root
    group: root
  become: yes
  become_user: root

- name: Install sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  become: yes
  become_user: root
