---
- include_tasks: mopidy_debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: mopidy_rh.yml
  when: ansible_os_family == "RedHat"

- name: Start and enable mopidy service
  systemd:
    name: mopidy
    state: started
    enabled: yes
  become: yes
