---
- name: Create .bash_logout
  copy:
    src: bash_logout
    dest: /home/{{ username }}/.bash_logout
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    force: yes
  become: yes
  become_user: root

- name: Create .bash_profile
  copy:
    src: bash_profile
    dest: /home/{{ username }}/.bash_profile
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    force: yes
  become: yes
  become_user: root

- name: Create .bashrc
  template:
    src: bashrc.j2
    dest: /home/{{ username }}/.bashrc
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    force: yes
  become: yes
  become_user: root

- name: Create .inputrc
  copy:
    src: inputrc
    dest: /home/{{ username }}/.inputrc
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    force: yes
  become: yes
  become_user: root
