---
- name: Install common packages
  dnf:
    name:
      - bash
      - curl
      - fuse
      - git
      - grep
      - mtr
      - rsync
      - ruby
      - stow
      - the_silver_searcher
      - tmux
      - vim-common
      - vim-enhanced
    state: latest
