---
- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  become: yes

- name: Install /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Install common packages
  package:
    name:
      - bash
      - curl
      - git
      - grep
      - htop
      - mtr
      - ripgrep
      - rsync
      - ruby
      - strace
      - tmux
      - vim-common
      - wget
    state: present
  become: yes

- include_tasks: redhat_common.yml
  when: ansible_os_family == "RedHat"

- include_tasks: ubuntu_common.yml
  when: ansible_os_family == "Debian"

- name: Create ~/tmp directory
  file:
    path: /home/{{ username }}/tmp
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  become: yes
  become_user: root

- name: Bash configuration
  import_tasks: bash_configuration.yml

- name: vim configuration
  copy:
    src: vimrc
    dest: /home/{{ username }}/.vimrc
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes
    mode: 0664
  become: yes
  become_user: root

- name: ssh authorized keys
  copy:
    src: authorized_keys
    dest: /home/{{ username }}/.ssh/authorized_keys
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes
    mode: 0600
  become: yes
  become_user: root

- name: Create local systemd directory
  file:
    path: /home/{{ username }}/.config/systemd/user
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0775
    recurse: yes
  become: yes
  become_user: root

- name: Create ~/.local/bin directory
  file:
    path: /home/{{ username }}/.local/bin
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0775
  become: yes
  become_user: root

- name: Copy git config
  template:
    src: gitconfig.j2
    dest: /home/{{ username }}/.gitconfig
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  become: yes
  become_user: root

- name: Remove pi user
  user:
    name: pi
    state: absent
    remove: yes
  become: yes
  become_user: root
