---
- name: Update all packages
  dnf:
    name: '*'
    state: latest

- name: Install common packages
  dnf:
    name:
      - bash
      - curl
      - git
      - grep
      - mtr
      - rsync
      - ruby
      - the_silver_searcher
      - tmux
      - vim-common
      - vim-enhanced
    state: latest

- name: Create {{ username }} user
  user:
    name: "{{ username }}"
    shell: /bin/bash
    state: present

- name: Bash configuration
  import_tasks: bash_configuration.yml

- name: vim configuration
  copy:
    src: vimrc
    dest: /home/{{ username }}/.vimrc
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes
    mode: 0664

- name: Create local systemd directory
  file:
    path: /home/{{ username }}/.config/systemd/user
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0775
    recurse: yes

- name: Create ~/.local/bin directory
  file:
    path: /home/{{ username }}/.local/bin
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0775

- name: Sync ansible repo
  git:
    dest: /home/{{ username }}/config
    repo: ssh://git@github.com:kylerjohnston/ansible.git
  become: yes
  become_user: "{{ username }}"
