---
- name: Install common packages
  dnf:
    name:
      - bash
      - curl
      - git
      - grep
      - mtr
      - rsync
      - ruby
      - the_silver_searcher
      - tmux
      - vim-common
      - vim-enhanced
    state: latest

  - name: Bash configuration
    import_tasks: bash_configuration.yml
