---
- name: Install Ubuntu common packages
  package:
    name:
      - netcat-traditional
      - python-setuptools
      - vim
  become: yes
  become_user: root

- name: Create {{ username }} user
  user:
    name: "{{ username }}"
    shell: /bin/bash
    state: present
    groups: sudo
  become: yes
  become_user: root
