---
- name: Install docker dependencies
  dnf:
    name:
      - dnf-plugins-core
      - grubby
    state: latest
  become: yes
  become_user: root

- name: Install docker-ce repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  become: yes
  become_user: root

- name: Install docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  become: yes
  become_user: root

- name: Enable cgroups exception
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  become: yes
  become_user: root

- name: Add me to the docker group
  user:
    name: '{{ username }}'
    groups: docker
    append: yes
  become: yes
