---
- name: Install Gnucash
  dnf:
    name:
      - sqlite
      - gnucash
    state: latest

- name: Copy Gnucash stylesheets
  copy:
    src: saved-reports-2.8
    dest: /home/{{ home_user }}/.local/share/gnucash/saved-reports-2.8
    owner: "{{ home_user }}"
    mode: 664
