---
- name: Install Texlive and pandoc
  dnf:
    name:
      - texlive-scheme-basic
      - texlive-collection-fontsrecommended
      - texlive-fira
      - texlive-fontawesome
      - texlive-moderncv
      - texlive-pdftex
      - pandoc
    state: latest

- name: Create ~/.pandoc
  file:
    path: /home/{{ username }}/.pandoc
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0775

- name: Clone pandoc-templates repo
  git:
    repo: ssh://git@github.com/kylerjohnston/pandoc-templates-1.git
    dest: /home/{{ username }}/.pandoc/templates
    accept_hostkey: yes
  become: yes
  become_user: "{{ username }}"
