---
- name: Install syncthing
  package:
    name: syncthing
    state: latest
  become: yes

- name: Start and enable syncthing
  systemd:
    name: syncthing@{{ username }}.service
    state: started
    enabled: yes
  become: yes
