---
- name: Install borg
  dnf:
    name: borgbackup
    state: latest

- name: Create borg mount point
  file:
    path: /mnt/borg
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Copy back2borg.sh script
  copy:
    src: back2borg.sh
    dest: /home/{{ username }}/.local/bin/back2borg.sh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy back2borg.service
  template:
    src: back2borg.service.j2
    dest: /home/{{ username }}/.config/systemd/user/back2borg.service
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0664

- name: Copy back2borg.timer
  copy:
    src: back2borg.timer
    dest: /home/{{ username }}/.config/systemd/user/back2borg.timer
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0664

- name: Enable back2borg.timer
  become: yes
  become_user: "{{ username }}"
  systemd:
    name: back2borg.timer
    enabled: yes
    scope: user
    state: started
    daemon_reload: yes
