---
- name: Install borg
  dnf:
    name: borgbackup
    state: latest

- name: Create ~/.local/bin if it does not exist
  file:
    path: /home/{{ username }}/.local/bin
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    mode: 0775

- name: Copy back2spinoza.sh script
  copy:
    src: back2spinoza.sh
    dest: /home/{{ username }}/.local/bin/back2spinoza.sh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    force: no

- name: Create ~/.config/systemd/user
  file:
    path: /home/{{ username }}/.config/systemd/user
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    mode: 0775

- name: Copy back2spinoza.service
  template:
    src: back2spinoza.service.j2
    dest: /home/{{ username }}/.config/systemd/user/back2spinoza.service
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0664

- name: Copy back2spinoza.timer
  copy:
    src: back2spinoza.timer
    dest: /home/{{ username }}/.config/systemd/user/back2spinoza.timer
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0664

- name: Enable back2spinoza.timer
  become: yes
  become_user: "{{ username }}"
  systemd:
    name: back2spinoza.timer
    enabled: yes
    state: started
